### PR TITLE
Set DF intent name to the action instead of name

### PR DESCRIPTION
**Pull request by akingbadeayobami**
**Proposed changes**:
- Default DF intent name to the response action instead of name

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
Thanks for submitting this PR, we'll give it a review as soon as possible. Could you elaborate a bit in your description what you're trying to do and why? It's a bit hard to understand as it is now

**Comment by akingbadeayobami** [comment]
The name for Dialoglow intents are stored at `responses[0].action` instead of `name` 
 This change is quite trivial for most use cases as the `name` is usually the `responses[0].action` but it becomes important when you have large number of examples for your intent.
 Dialogflow caps the number of examples you can place in a file(`name`) to about 2000 but no limit is placed for the number of examples for an action
 Hence if you have about 5000 examples for an intent, you will be able to use different names but still be able to set the action to the same in the `responses[0].action`
 But since RASA gets the intent name from the `name` this will not be possible
I also added a fallback to the `name` in the case where `responses[0].action` is not found

**Comment by akelad** [comment]
@akingbadeayobami any reason you closed this?

**Comment by akingbadeayobami** [comment]
@akelad 
We were of the thought that you guys might not accept the PR as other people using dialogflow import might already expect that they’ll receive the intent name and not an action and this will be a breaking change for them
so we fix the issue in our build process and then close the PR

**Comment by akelad** [comment]
alright, sounds good

**Pull request closed without merging**
