### PR TITLE
FAQ handling

### PR DESCRIPTION
**Pull request by tmbo**
**Goal**:
Properly handle FAQ like interactions

**Proposed changes**:
- new model for FAQ classification
- model to decide if an input is FAQ or normal sentence

**Todo**:
- [ ] find a good ML model for FAQ classification. Currently:  kNN does work - need to check if it is stable enough
- [ ] model for sentence <-> faq classification
- [ ] testing and documentation updates

**Status**:
currently in development

- [ ] ready for code review
- [ ] there are tests for the functionality
- [ ] documentation updated
- [ ] changelog updated

### CODE REVIEW

**Comment by jithurjacob** [comment]
@tmbo Could you please explain the approach you are planning to take for building an FAQ classifier?

**Comment by sankethpb** [comment]
@tmbo Could you please clarify if this would be worked upon later?

**Comment by Running-He** [comment]
may I know the most update status on this？

**Comment by tmbo** [comment]
We haven't looked at this for a while now, but as far as I know, the intent embedding classifier may do an equally well job in classifying faq questions.

**Pull request closed without merging**
