### PR TITLE
Error Logging, Confidence Histogram, Auto-Save

### PR DESCRIPTION
**Pull request by RolandJAAI**
As discussed with @amn41 :
- added logging of samples which are not classified correctly to make
debugging easier (shows in log and saved to file)
- added a histogram of confidence level of predictions to choose
threshold for „I did not understand that question“ and as indication of
model robustness
- added auto-saving of confusion matrix plot to file

**Status (please check what you already did):**
- [x] made PR ready for code review
- [ ] added some tests for the functionality 
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by AbdurRub** [comment]
Great! adding logging of samples which are not classified correctly to make
debugging easier.

**Comment by tmbo** [comment]
Sorry that this was stale for so long. I'll close this PR as there is a merge conflict with the current master version. If you still want to add this feature, please fix the merge commit and let me know so I can reopen this.

**Comment by amn41** [comment]
@RolandJAAI I'd still be very keen to see this merged in. Would you be up for creating a new PR with this in it?

**Comment by RolandJAAI** [comment]
@amn41 @tmbo Yes, I will update the error logging asap to work with the master version. For us this is a really important feature to debug the NLU. I will leave the auto-save and confidence histogram aside for now as this is interesting but rather optional for most users.

**Comment by amn41** [comment]
if possible I'd love to get the histogram in there too!

**Comment by RolandJAAI** [comment]
Here is the new version including histogram ;) https://github.com/RasaHQ/rasa_nlu/pull/1277

**Pull request closed without merging**
