### PR TITLE
Phrase matcher

### LINKED ISSUE #773: gazetteer support
**Proposed Improvement**:
Add another entity extractor component that makes use of gazetteers, i.e. list of known entities. Such a component would be useful if you have a large number of entities that you know upfront, e.g.  an index of all the streets in a city or a list of dishes on a menu. Could be an alternative to filling your training data with lots of templated and similarly structured sentences for training.

Possible extensions
* fuzzy matching (also matching variants up to edit distance X)
* combination with the regex component to define regexes in combination with each instance in the entity list, e.g. streetname + streetnumber?
* integration as a feature into the crf model - so the crf could accept or overwrite the gazetteers finding

Thoughts?

### PR DESCRIPTION
**Pull request by twerkmeister**
**Proposed changes**:
- fixes #773 

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog

### CODE REVIEW

**Comment by twerkmeister** [comment]
@alan any remarks, or should I go ahead write the docs?

**Comment by amn41** [comment]
functionality looks super userful - do please make a start on a docs :)

**Comment by twerkmeister** [comment]
Ok it is almost done, but I realized that there's one remaining problem. The way it is implemented right now, the phrase matcher is applied to the text directly without previous segmentation. For Chinese/Japanese (which I have been thinking about mostly) this would be useful to get around the segmentation errors. However, in english, for short phrases this is likely to lead to extracting entities from within words. I don't think this is desirable.
We could
* use tokenization generally, but that might cost us performance for Chinese and Japanese
* use tokenization depending on the language
* maybe something else
I'll think of other options. Thoughts?

**Comment by tmbo** [comment]
I think we need to better support the use case where the string is tokenized and entities should span tokens - I'd be fine with the creation of a config variable to decide if tokenization should be used or not.

**Comment by kunalm37** [comment]
This is a super useful feature, please work on this to add this to the master branch.

**Comment by ctrado18** [comment]
I would like this feature too! Is it possible to connect the phrase-matcher entities with a external file instead of typing all values manually? As I understood from the docs you have to specify all available entities also in the phrase-matcher place. But also with the entities' values such that all values do have to appear inside this list?

**Comment by AbdurRub** [comment]
When we are expecting this to merge?

**Comment by AbdurRub** [comment]
What a great feature!  Thumbs up Team RASA. 
I tested branch phrase matcher. working fine with my use case.
Is there any possibility we can get it done in separate file rather than putting it in training data?
Plus I observed it was detecting entities from both ner_crf and ner_phrase_matcher.  what if we just show one with best prediction? Just asking.  and why it is not merge to master yet?

**Comment by ctrado18** [comment]
I agree! I run often then in the situation where ner_crf and phrase matcher finds an entiy. So one gets overwritten.

**Comment by AbdurRub** [comment]
When we are expecting this to be merged?

**Comment by twerkmeister** [comment]
Sorry everyone for waiting so long for this, I was blocked the last two months, but now I am back on it!

**Comment by kunalm37** [comment]
Looks like a very promising feature, when can we expect this to be merged? @twerkmeister @tmbo  @amn41

**Comment by ctrado18** [comment]
Would it be possible to call this phrase matcher in a custom way such that it will be only exectuded after no enity is recognized from NLU (such as a fallback)?

**Comment by twerkmeister** [comment]
@ctrado18 You could implement priority rules if entities overlap yourself and apply them to NLU output. This should work if you only use NLU and also with adding a small component between NLU and core.

However, it might make sense to come up with some component that generally handles conflict resolution for entities on our side, i.e. deciding what happens if two extractors have found two overlapping but unequal entities. @amn41 @tmbo  we don't have something like this as of now, right?

**Comment by AbdurRub** [comment]
When its going to be merged?  anxiously waiting!

**Comment by amn41** [comment]
@twerkmeister I think something to disambiguate should probably be a custom component, don't think it's something we should implement

**Comment by twerkmeister** [comment]
Alright, I need a review then @amn41 @tmbo  ^^

**Comment by tmbo** [comment]
On my list

**Comment by ashwinbiyani** [comment]
By seeing GitHub check-ins I have got some usage idea. I think it is adding a simple pipeline called  **ner_phrase_matcher**

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
**- name: "ner_phrase_matcher"**


**I am getting below error when I run rasa NLU train command. rasa version is 0.12. is this change rolled out?**

(base) E:\projects\rasa\rasa_core-master\examples\remotebot>python -m rasa_nlu.train -c nlu_model_config.json -d data\MAYA_Original --path projects
Traceback (most recent call last):
  File "E:\Softwares\anaconda3\lib\site-packages\rasa_nlu\registry.py", line 107, in get_component_class
    return utils.class_from_module_path(component_name)
  File "E:\Softwares\anaconda3\lib\site-packages\rasa_nlu\utils\__init__.py", line 175, in class_from_module_path
    return globals()[module_path]
KeyError: 'ner_phrase_matcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Softwares\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\Softwares\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Softwares\anaconda3\lib\site-packages\rasa_nlu\train.py", line 163, in <module>
    num_threads=cmdline_args.num_threads)
  File "E:\Softwares\anaconda3\lib\site-packages\rasa_nlu\train.py", line 136, in do_train
    trainer = Trainer(cfg, component_builder)
  File "E:\Softwares\anaconda3\lib\site-packages\rasa_nlu\model.py", line 146, in __init__
    components.validate_requirements(cfg.component_names)
  File "E:\Softwares\anaconda3\lib\site-packages\rasa_nlu\components.py", line 54, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "E:\Softwares\anaconda3\lib\site-packages\rasa_nlu\registry.py", line 116, in get_component_class
    "in a module.".format(component_name))
Exception: Failed to find component class for 'ner_phrase_matcher'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa_nlu.registry.py` or is a proper name of a class in a module.

**is this change rolled out. Are we missing something here?**

**Comment by tmbo** [comment]
I took another look at the code and the code itself is looking good, I am more worried about the general idea of adding another pattern matching component.

I am not convinced we really need this:
- can't the user specify the lists as regex patterns (`(apple|ibm|samsung)`)
- won't the CRF entity extractor pick most of this up as well given that it is looking at 5 character prefixes

**Comment by amn41** [comment]
looking at these results https://github.com/RasaHQ/rasa_nlu/issues/1144 what we currently have isn't working for people. though not sure if it's a usability issue or a model issue

**Comment by twhughes** [comment]
Hi @twerkmeister , I'm trying to test this PR right now on a super simple example.  However, I keep getting the same entity extraction results whether or not I include `entity_phrase` in the training data.  Could you take a quick look?  

My config:

    language: "en"
    pipeline:
       - name: "nlp_spacy"
       - name: "tokenizer_spacy"
       - name: "ner_phrase_matcher"

My training data:

    ## intent:restaurant_search
    - i'm looking for a [sushi](food) place to eat
    - I want to grab [bibimbap](food)
    - I am searching for a [pizza](food) spot
    - i'm looking for a place in the north of town with [cheeseburgers](food)
    - show me [dumpling](food) restaurants
    - show me chines restaurants that serve [duck](food) in the north
    - show me a mexican place in the centre with [nachos](food)
    - i am looking for an indian spot called olaolaolaolaolaola
    - search for restaurants
    - anywhere in the west
    - anywhere near 18328
    - I am looking for asian fusion food like [rolls](food)
    - I am looking a restaurant in 29432 that has [bunelos](food)
    - I am looking for mexican indian fusion with [burritos](food)
    - Gimme them [tacos](food)
    - central indian restaurant has [lentils](food)
    - I want something with [Mapo Tofu](food)

    ## entity_phrase:food
    * Mapo Tofu
    * Tacos
    * Chana Masala
    * lentils
    * pizza
    * sushi

I'm doing cross validation on this

    python -m rasa_nlu.evaluate --mode crossvalidation -d path/to/data -c /path/to/config

And i get the same exact results whether or not I delete the entire `entity_phrase:food`

Do you see any issues with my setup?  Perhaps I dont understand the functionality 100% yet. 

Thanks

**Comment by twerkmeister** [comment]
@twhughes Good catch, the problem was that in the eval script entity_phrases weren't copied into the new dataset after splitting. So basically both of your tests ran with empty entity phrases. It works now 👍

**Comment by twerkmeister** [comment]
@tmbo I agree that the phrase matcher shouldn't be overused. To me the strength of the component is when you have a long list of entities that might span variable numbers tokens. The use case that I was struggling with was street names. They come in all sorts of varieties, token lengths, etc.

I just looked into the regex featurizer, and to be fair, it seems it should be able to do something very similar. The only downside I see would be that it is nicer to have a long markdown list than a 1000 lines regex text blob, but actually you could just feed the entity phrases into the regex featurizer. The only other thing is, that the phrase matcher works even when there is 0 context and you get a definite match, but afterall I think it might be worth doing a test with the regex featurizer.

@twhughes since you are doing some test run with the phrase matcher right now, would you mind comparing it to having your city list as a long regex feature?

**Comment by twhughes** [comment]
@twerkmeister  & @tmbo  Yea I can look into this.  And I just tested the new commit and it works.  

Thanks!

**Comment by tmbo** [comment]
implemented as part of #1312

**Pull request closed without merging**
