### PR TITLE
Remove /config endpoint

### PR DESCRIPTION
**Pull request by stranger26**
**Proposed changes**:
- #1132 

**Status (please check what you already did)**:
- [X] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
Thanks for submitting this PR, i'm not sure we want to remove this just yet though -- @tmbo ?

**Comment by tmbo** [comment]
I think it is fine to remove it, needs to be added to changelog & migration guide though.

**Comment by akelad** [comment]
cool, @stranger26 could you add it to the changelog and migration guide please?

**Comment by stranger26** [comment]
@akelad alright!

**Comment by akelad** [comment]
Cool thanks, no need to include the issue number in the changelog. Could you still take a look why the build is failing? I assume there's a test for the `/config` endpoint that needs to be removed

**Comment by tmbo** [comment]
Oh, this just means travis got stuck...happens some times. I'll restart the build.

**Pull request merged**
