### PR TITLE
Replaced flask http server with klein

### PR DESCRIPTION
**Pull request by PHLF**
This is a working proposal. I struggled a lot with the actual implementation just by trying to add a freshly trained model  to the config's `server_model_dirs` variable after a call to the `/train` http endpoint. Indeed it escalated quickly into a multiprocessing management hell whereas Klein non blocking request handling model would have been far easier to use.

I didn't have time to write some asynchronous request handling using Twisted Deferred objects, so this is just a basic replacement.

What do you think?

**Proposed changes**:
- Replaced the Flask http server with Klein

**Status**:
- [X] ready for code review
- [ ] there are tests for the functionality
- [ ] documentation updated
- [ ] changelog updated

### CODE REVIEW

**Comment by tmbo** [comment]
Cool idea. I haven't tried out Klein before, so please bare with me if theses questions are foolish. Looking at the diff I can't yet see any benefit (yet) of using Klein. I know you said this is just porting it - but I'd like to better understand what the advantage of using it is. Wouldn't we still run into the same multi-processing issues as before?

**Comment by tmbo** [comment]
Yes that makes total sense. Thanks a lot for the detailed explanation. To estimate the impact of the switch it would be helpfull to have a performance comparison between the flask version (running in gunicorn) and the Klein version. Would you mind taking a look at that?

**Comment by PHLF** [comment]
On my computer, using this simple bash script:  
```bash
#!/bin/bash
for i in `seq 1 100`;
do
   curl --silent -H "Content-Type: application/json" -X POST -d '{"q":"Hello there"}' localhost:5000/parse >> /dev/null
done
```

Over 10 runs using twisted-klein:  
```
real    0m2.908s
user    0m0.438s
sys     0m2.141s

real    0m3.014s
user    0m0.375s
sys     0m2.172s

real    0m2.939s
user    0m0.250s
sys     0m2.297s

real    0m2.948s
user    0m0.266s
sys     0m2.406s

real    0m2.906s
user    0m0.234s
sys     0m2.266s

real    0m2.993s
user    0m0.297s
sys     0m2.188s

real    0m2.961s
user    0m0.422s
sys     0m2.156s

real    0m3.290s
user    0m0.219s
sys     0m2.484s

real    0m3.008s
user    0m0.391s
sys     0m2.156s

real    0m3.013s
user    0m0.250s
sys     0m2.188s
```

Over 10 runs using gunicorn on 4 processes with 12 threads:
```
real    0m3.875s
user    0m0.375s
sys     0m1.906s

real    0m2.481s
user    0m0.313s
sys     0m1.969s

real    0m3.088s
user    0m0.438s
sys     0m1.891s

real    0m2.816s
user    0m0.438s
sys     0m1.859s

real    0m2.497s
user    0m0.516s
sys     0m1.797s

real    0m2.490s
user    0m0.500s
sys     0m1.703s

real    0m2.483s
user    0m0.375s
sys     0m1.906s

real    0m2.477s
user    0m0.453s
sys     0m1.734s

real    0m3.854s
user    0m0.297s
sys     0m2.031s

real    0m2.795s
user    0m0.500s
sys     0m1.844s
```
Real times means:
-  twisted-klein:  2.998s
-  flask: 2.886s

However I didn't expect twisted-klein to outperform flask when it comes to handling a high throughput: like I said there are other frameworks achieving the same purpose and faster like tornado or sanic but they either don't have an api looking like flask's or they are Python 3 only 😐

**Comment by tmbo** [comment]
This only evaluates the sequential performance, doesn't it? Usually, we are more interested in the value requests / sec by keeping the time / req reasonably small.

It is not so much about millisecond performance of the framework. Rather, there needs to be a straightforward way to e.g. employ the power of a 8 core server in a reasonable way.

**Comment by PHLF** [comment]
If you like to see performance improvment,

**Pull request closed without merging**
