### PR TITLE
add Swagger v2 and OpenAPI v3 interfaces

### PR DESCRIPTION
**Pull request by SteffenLuypaert**
**Proposed changes**:
Please see https://github.com/RasaHQ/rasa_nlu/issues/672

**Status**:
- [x] made PR ready for code review
- [-] added some tests for the functionality -> I tested the specs using swagger-codegen locally but I don't see how I can write unit tests for them without bloating your repo and spending a lot of time setting them up
- [x] updated the documentation - I added a readme markdown for the folder I added, I don't think the change should be mentioned in the main documentation?
- [x] updated the changelog

### CODE REVIEW

**Comment by wrathagom** [comment]
We'll need @tmbo or someone's review, but I can tell you that several of the endpoints are incompletely documented (probably are in the basic docs as well) because most configuration parameters can be passed to `/train`

Should we do the work so that the swagger site comes up when someone starts the rasa nlu server?

Lastly, my guess is that @tmbo may have reservations about merging this in just out of fear that it wont be maintained.

**Comment by SteffenLuypaert** [comment]
Hello, thanks for the reply. 

I mostly based myself on the docs and deduced some things while testing the interface. I might be missing some undocumented input properties. Do you have an example of a json for the train call that contains config parameters?

With the Swagger site you mean the generated api description as when you load in on tools like editor.swagger.io? That could be done but I'm not sure that the main project collaborators would agree with that change.

About maintaining the interface: as long as we are using Rasa ourselves, I have no problem maintaining it, since we prefer to have an up to date client, but I understand such concern. If I should make it available somewhere else, please let me know and I'll put it there and I'll decline the pull request.

**Comment by tmbo** [comment]
Thanks a lot for the time you have put into creating these markups.

As much appreciated as these descriptions are, as long as they are not generated automatically in some way they will get out of sync. So to prevent that:
- I'd only add one of them (probably the more recent version v3)
- either generate them automatically from code or there should be tests to make sure the spec is up to date with the code.

**Comment by tmbo** [comment]
I'll close this for the time being. Let me know if you still intent to update this PR

**Pull request closed without merging**
