### PR TITLE
return the jieba tokens

### PR DESCRIPTION
**Pull request by smapley**
**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
Thanks a lot for submitting this pull request, we'll give it a review as soon as possible

**Comment by tmbo** [comment]
@smapley why would we need to add the tokens to the output json?

**Comment by smapley** [comment]
@tmbo 1. Sometimes,in the testing process,we should know the tokens to help us to modify the Custom dictionary.
2. When processing voice logs, you can get the intent and tokens directly，however if we mark the wrong data, we do not repeat it.

**Comment by howl-anderson** [comment]
Add a switch option to jieba component will be better I think. Users can choose to turn on or turn off this feature.

**Comment by howl-anderson** [comment]
Or we need a debug or verbose mode for output more detailed information for all component to output JSON?

**Comment by tmbo** [comment]
I like that idea of having a general flag that enables returning all the attributes - I think that could work

**Comment by tmbo** [comment]
I'll close this in favor of a PR that implements this in a more general way.

**Pull request closed without merging**
