### PR TITLE
fix for the issue #1298 

### PR DESCRIPTION
**Pull request by esrel**
Fix for the issue #1298 (namedtuple bug in evaluate.py)  on all-zero embedding vectors and replacing None with empty string in evaluation script 

**Proposed changes**:
- replace line 176 in evaluate.py with r = r._replace(prediction="")

**Status (please check what you already did)**:
- [X] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
Thanks for this, do you mind signing the CLA?

**Comment by esrel** [comment]
I did sign actually. At least it says that I did.

**Comment by akelad** [comment]
for me it says you haven't, i think you need to add your email address you used to your GH account:
screen shot 2018-08-13 at 09 43 47

**Comment by esrel** [comment]
Did it again with making email address public. Hope it will work.
screen shot 2018-08-13 at 09 57 28

**Pull request merged**
