### PR TITLE
Add failed status to project

### PR DESCRIPTION
**Pull request by CarolWu1206**
**Proposed changes**:
- https://github.com/RasaHQ/rasa_nlu/issues/1522#issue-379637197

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
Thanks for submitting this PR, we'll give it a review as soon as possible

**Comment by tmbo** [comment]
@CarolWu1206 is this ready for another review?

**Comment by CarolWu1206** [comment]
Yes.

**Comment by CarolWu1206** [comment]
Is there anything I have to do to merge this PR?

**Comment by huberrom** [comment]
I just had the following issue with rasa nlu 0.13.8, is this linked ? Because it seems merged

```
2019-02-26 16:04:58+0000 [-] 2019-02-26 16:04:58 WARNING  rasa_nlu.data_router  - [Failure instance: Traceback (failure with no frames): &lt;class 'concurrent.futures.process.BrokenProcessPool'&gt;: A process in the process pool was terminated abruptly while the future was running or pending.
2019-02-26 16:04:58+0000 [-] ]
/usr/local/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
 len(cache))
2019-02-26 16:04:58+0000 [-] Unhandled Error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
        self._startRunCallbacks(fail)
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
        self._runCallbacks()
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
        _inlineCallbacks(r, g, status)
    --- &lt;exception caught here&gt; ---
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/app/rasa_nlu/server.py", line 362, in train
        RasaNLUModelConfig(model_config), model_name)
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/app/rasa_nlu/data_router.py", line 356, in training_errback
        failure.value.failed_target_project)
    builtins.AttributeError: 'BrokenProcessPool' object has no attribute 'failed_target_project'
```

**Pull request merged**
