### PR TITLE
Added API.ai export format handling

### PR DESCRIPTION
**Pull request by deubaka**
**Proposed changes**:
- Added new API.ai export data handling (added new 'language' in `load_data`, defaults to `en`)
- Added new API.ai export training and test data (English and Spanish only)
- Updated/named current API.ai old to `api_legacy` and new as `api` (added deprecation for `api_legacy`)

> Note: I opted to add an additional parameter (which defaults to `en`), `language`, in `load_data` as I didn't want to import the `config` into `converters.py`. However, I still feel it's not the best solution. :/

**Status**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [x] updated the documentation
- [ ] changelog updated

### CODE REVIEW

**Comment by deubaka** [comment]
Just this morning, API.ai is now **[DialogFlow](https://developers.googleblog.com/2017/10/introducing-dialogflow-new-name-for.html)**. Will be needing to update the codes and docs again (returning `api_legacy` to just `api` and have a new `dialogflow` data format).

**Comment by tmbo** [comment]
There was an issue with travis and mongodb (mongo let their package certificate expire...), mind to merge in `master`?

**Comment by deubaka** [comment]
@tmbo Just to clarify on `mind to merge in master?`. Do you mean I merge my current PR/branch directly to `RasaHQ:master` and push it directly right?

**Comment by tmbo** [comment]
The other way around. It would be good if you could merge the master branch into your branch to get the travis update propagated to your branch.

**Comment by deubaka** [comment]
@tmbo I was a bit confused about it, glad I did clarify. 

Just did the merge and ran again, but running into a failing test, on the Spanish `es` test training data. Locally I've tested it without issue though (both on 2.7 and 3.6). I'm running `pytest tests/base/test_training_data.py`, which is passing on my machine.

**Comment by tmbo** [comment]
Looks good - thanks for all the energy you have put into this :rocket: 😃

**Pull request merged**
