### PR TITLE
Better YAML code style for .travis.yml

### PR DESCRIPTION
**Pull request by howl-anderson**
**Proposed changes**:
- better YAML style for reading and maintenance

**Status (please check what you already did)**:
- [x] made PR ready for code review

### CODE REVIEW

**Comment by tmbo** [comment]
Cool, anything else you want to do as part of this PR (WIP)?

**Comment by howl-anderson** [comment]
So far so good. When I come up with some new ideas, I will send other PR. Thanks.

**Comment by tmbo** [comment]
sounds good :+1:

**Comment by tmbo** [comment]
Thanks a lot, makes it way more readable :rocket:

**Pull request merged**
