### PR TITLE
Add analyzer to vectorizer

### LINKED ISSUE #1217: featurizer_count_vectors with words and N-Grams?
Hey,

I need to use N-Grams with featurizer_count_vectors , but I think it would improve importantly the classification if you could also use it together with word itself. Such that not trained words like for the tensorflow_embedding have a chance if they have specific ngrams. 

Can you this easily within the pipelin or is just one possible at the moment?

```
pipeline:
- name: "intent_featurizer_count_vectors"
  analyzer: 'char'
  "min_ngram": 2  # int
  "max_ngram": 3  # int
```

Can you put the featurizer as a series, such that first it creates features with words then you put again in the pipeline the featurizer for `char`?

```
pipeline:
- name: "intent_featurizer_count_vectors"
  analyzer: 'char'
  "min_ngram": 2  # int
  "max_ngram": 3  # int
- name: "intent_featurizer_count_vectors"
  analyzer: 'word'

```

EDIT:

I tried the `intent_featurizer_ngrams` after `intent_featurizer_count_vectors` in my pipeline:

```
language: "de_core_news_sm"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_count_vectors"
- name: "intent_featurizer_ngrams"
  # Maximum number of ngrams to use when augmenting
  # feature vectors with character ngrams
  max_number_of_ngrams: 5
- name: "intent_classifier_sklearn"
```
But this gives error:

```
Traceback (most recent call last):
  File "C:\Users\\Anaconda3\envs\rasa12\lib\site-packages\rasa_nlu\model.py", line 340, in parse
    component.process(message, **self.context)
  File "C:\Users\\Anaconda3\envs\rasa12\lib\site-packages\rasa_nlu\featurizers\ngram_featurizer.py", line 88, in process
    updated = self._text_features_with_ngrams(message, self.best_num_ngrams)
  File "C:\Users\\Anaconda3\envs\rasa12\lib\site-packages\rasa_nlu\featurizers\ngram_featurizer.py", line 97, in _text_features_with_ngrams
    return self._combine_with_existing_text_features(message, extras)
  File "C:\Users\\Anaconda3\envs\rasa12\lib\site-packages\rasa_nlu\featurizers\__init__.py", line 18, in _combine_with_existing_text_features
    additional_features))
  File "C:\Users\Anaconda3\envs\rasa12\lib\site-packages\numpy\core\shape_base.py", line 288, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input arrays must have same number of dimensions
```

### LINKED ISSUE #1494: Check whether Subword Semantic Hashing improve performance of tf flu classifier
The idea is from the paper: https://arxiv.org/pdf/1810.07150.pdf

It should work with current implementation, but using character ngrams in `CountVectorizer`

### LINKED ISSUE #1530: Feature Request: character_count_vectorizer_
**Feature Request**:
It would be useful to have a separate `intent_featurizer_count_char_vectors` (or similarly named) Component. Using a separate Component makes it simple to combine them using defaults (mixing defaults across char- and word-level `CountVectorizer` is messy since they're very different). 

**Sample**:
```yml
  - name: "intent_featurizer_count_vectors"
    max_features: 1000
    min_ngram: 1  # int
    max_ngram: 2  # int

  - name: "charcountvectorizer.charcountvectorizer.CharCountVectorsFeaturizer"
    max_features: 1000
    analyzer: "char"
    min_ngram: 1
    max_ngram: 6
```
This config file would create features for the top 1000 *word* uni- and bi-grams, then would supplement that with the top 1000 *character* uni- to 6-grams. I've tested this with my own data and confirmed it does imbue the pipeline with some spelling/typo invariance. Obviously once it's default component we can name it something better than it is above.

The only changes I think are necessary are:
1) base the new component off `CountVectorFeaturizer`
2) add 'analyzer' argument
3) edit new defaults
4) update `.load` to reference itself instead of `CountVectorFeaturizer`
5) add it to the registry

Could address #1217 and #1494

### PR DESCRIPTION
**Pull request by jamesmf**
**Proposed changes**:
- add `analyzer` argument to CountVectorsFeaturizer
- fixes #1530
- fixes #1217
- fixes #1494 

**Status (please check what you already did)**:
- [X] made PR ready for code review
- [X] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by Ghostvv** [comment]
Thank you for this PR. Did you perform any analytics on how it improves the performance? If so could you please post here the results?

**Comment by jamesmf** [comment]
No - is there standard test data for that?

**Comment by Ghostvv** [comment]
no, I was just curious if you performed any performance tests

**Comment by Ghostvv** [comment]
can I ask why did you close this PR? Do you plan to open another one?

**Comment by jamesmf** [comment]
really sorry, but after reading the CLA I realized that I am not familiar enough with my organization's policy regarding open source, so I have to close the PR/delete the branch for now. Sorry to have wasted your time -- hopefully in the future I will be certain that I'm able to contribute.

**Pull request closed without merging**
