### PR TITLE
Improved style and created one training section

### PR DESCRIPTION
**Pull request by tmbo**
**Proposed changes**:
- replace split training sections (`intent_examples`, `entity_examples`, `common_examples`) with one section for training data called `training_examples`
- some style improvements
- read language from metadata instead of config for loaded duckling component

**Status**:
- [x] ready for code review
- [x] there are tests for the functionality
- [x] documentation updated
- [x] changelog updated

### CODE REVIEW

**Comment by amn41** [comment]
two thoughts:
- this will break the nlu-trainer interface since it looks for the 'common_examples' in the json
- is there still a way to avoid unbalanced classes in the intent classification?

**Comment by tmbo** [comment]
@amn41 so the common example section will still be read. 

I don't think the current setup is a good solution for the unbalanced classes issue:
- it's tedious as you manually need to keep track of the number of examples and ensure balance
- given that we do one-vs-rest training I'd argue that the imbalance is an issue either way
- users don't get it.

I'd hence go for an automatic solution. E.g. for the sklearn svm we could think about setting the `class_weight` parameter to `balanced` which will weight each training example inversely proportional to the number of examples in that class.

**Comment by amn41** [comment]
@tmbo ok I actually agree with both your points. I think more damage is probably caused by this confusion than by unbalanced training

**Comment by tmbo** [comment]
What do you think about the `common_examples` vs `training_examples`? I mean we could also continue to use the `common_examples` name, might make it easier for e.g. the trainer

**Comment by amn41** [comment]
we can move to `training_examples`, and update the trainer to look for either :)

**Pull request merged**
