### PR TITLE
Debugmessage

### LINKED ISSUE #3177: Debugging message for current slots filled is misleading as it is currently displayed
For example if you restart, it prints the slots as of before they are reset: 
```
Your input ->  /restart
2019-03-29 13:20:46 DEBUG    rasa_core.tracker_store  - Recreating tracker for id 'default'
2019-03-29 13:20:46 DEBUG    rasa_core.processor  - Received user message '/restart' with intent '{'name': 'restart', 'confidence': 1.0}' and entities '[]'
2019-03-29 13:20:46 DEBUG    rasa_core.processor  - Logged UserUtterance - tracker now has 24 events
2019-03-29 13:20:46 DEBUG    rasa_core.processor  - Current slot values:
	facility_address: None
	facility_id: None
	facility_type: rbry-mqwu
	location: atlanta
	requested_slot: None
2019-03-29 13:20:46 DEBUG    rasa_core.processor  - Predicted next action 'action_restart' with prob 1.00.
2019-03-29 13:20:46 DEBUG    rasa_core.processor  - Action 'action_restart' ended with events '['Restarted()']'
2019-03-29 13:20:46 DEBUG    rasa_core.processor  - Predicted next action 'action_listen' with prob 1.00.
```

And when using forms and setting `auto_fill` to `false` it looks like the entity didn't get detected since slots are seemingly always a step behind. 

This can be fixed by simply moving the print statements a bit later in the process to have a more useful update in the print message that is not lagging.

### PR DESCRIPTION
**Pull request by paulaWesselmann**
**Proposed changes**:
-fixes #3177 

Instead of only showing the first "Current slot values" now the second ones are shown, so after they are updated. 
```
Your input ->  /restart
2019-03-29 17:15:29 DEBUG    rasa_core.tracker_store  - Recreating tracker for id 'default'
2019-03-29 17:15:29 DEBUG    rasa_core.processor  - Received user message '/restart' with intent '{'name': 'restart', 'confidence': 1.0}' and entities '[]'
2019-03-29 17:15:29 DEBUG    rasa_core.processor  - Logged UserUtterance - tracker now has 13 events
2019-03-29 17:15:29 DEBUG    rasa_core.processor  - Current slot values:
	cuisine: italian
	feedback: None
	num_people: None
	outdoor_seating: None
	preferences: None
	requested_slot: num_people
2019-03-29 17:15:29 DEBUG    rasa_core.processor  - Predicted next action 'action_restart' with prob 1.00.
2019-03-29 17:15:29 DEBUG    rasa_core.processor  - Action 'action_restart' ended with events '['Restarted()']'
2019-03-29 17:15:29 DEBUG    rasa_core.processor  - Current slot values:
	cuisine: None
	feedback: None
	num_people: None
	outdoor_seating: None
	preferences: None
	requested_slot: None
```

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by paulaWesselmann** [comment]
I don't know what happend here I must have pushed from the wrong repo. I'll close this

**Comment by akelad** [comment]
@paulaWesselmann i'm a bit confused by your comments here -- did we move the slot logging or did you want them to be logged twice?

**Comment by paulaWesselmann** [comment]
I moved the logging message now, so that it makes more sense for debugging, since it is run after every action now (user or bot) it will print twice, now it shows the user the most current slots too and isn't lagging anymore.

**Comment by akelad** [comment]
hmm i do think it's good that they're shown after an action is executed now, but not sure they should be shown after an action listen.. it's a lot of slot prints:
```
Your input ->  greek cuisine                                                                       
2019-04-02 11:51:32 WARNING  asyncio  - Executing <Handle <TaskWakeupMethWrapper object at 0x14ad92f48> created at /Users/oakela/Documents/RASA/killer-demo/venv3/lib/python3.6/site-packages/aiohttp/helpers.py:656> took 4.548 seconds
2019-04-02 11:51:32 WARNING  asyncio  - Executing <Handle <TaskWakeupMethWrapper object at 0x14d2bf618> created at /Users/oakela/Documents/RASA/killer-demo/venv3/lib/python3.6/site-packages/sanic/server.py:721> took 0.001 seconds
2019-04-02 11:51:32 WARNING  asyncio  - Executing <Task pending coro=<SanicPluginsFramework._handle_request() running at /Users/oakela/Documents/RASA/killer-demo/venv3/lib/python3.6/site-packages/spf/framework.py:476> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x14d2bf0a8>()] created at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/queues.py:164> created at /Users/oakela/Documents/RASA/killer-demo/venv3/lib/python3.6/site-packages/sanic/server.py:333> took 0.002 seconds
2019-04-02 11:51:32 DEBUG    rasa.core.agent  - created a new lock for conversation 'default'
2019-04-02 11:51:32 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'default'
2019-04-02 11:51:32 DEBUG    rasa.core.processor  - Received user message 'greek cuisine' with intent '{'name': 'inform', 'confidence': 0.9999457539261046}' and entities '[{'start': 0, 'end': 5, 'value': 'greek', 'entity': 'cuisine', 'confidence': 0.9244117542918504, 'extractor': 'CRFEntityExtractor'}]'
2019-04-02 11:51:32 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 13 events
2019-04-02 11:51:32 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'intent_inform': 1.0, 'prev_utter_on_it': 1.0}, {'intent_inform': 1.0, 'prev_utter_ask_cuisine': 1.0}, {'intent_inform': 1.0, 'prev_action_listen': 1.0, 'slot_cuisine_0': 1.0, 'entity_cuisine': 1.0}]
2019-04-02 11:51:32 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2019-04-02 11:51:32 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_2_RestaurantPolicy
2019-04-02 11:51:32 DEBUG    rasa.core.processor  - Predicted next action 'utter_ask_location' with prob 0.99.
2019-04-02 11:51:32 DEBUG    rasa.core.processor  - Action 'utter_ask_location' ended with events '[]'
2019-04-02 11:51:32 DEBUG    rasa.core.processor  - Current slot values: 
	cuisine: greek
	info: None
	location: None
	matches: None
	people: None
	price: None
2019-04-02 11:51:32 DEBUG    rasa.core.processor  - Bot utterance 'BotUttered(text: where?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
2019-04-02 11:51:32 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'intent_inform': 1.0, 'prev_utter_ask_cuisine': 1.0}, {'intent_inform': 1.0, 'prev_action_listen': 1.0, 'slot_cuisine_0': 1.0, 'entity_cuisine': 1.0}, {'intent_inform': 1.0, 'prev_utter_ask_location': 1.0, 'slot_cuisine_0': 1.0, 'entity_cuisine': 1.0}]
2019-04-02 11:51:32 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2019-04-02 11:51:32 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_2_RestaurantPolicy
2019-04-02 11:51:32 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with prob 0.99.
2019-04-02 11:51:32 DEBUG    rasa.core.processor  - Action 'action_listen' ended with events '[]'
2019-04-02 11:51:32 DEBUG    rasa.core.processor  - Current slot values: 
	cuisine: greek
	info: None
	location: None
	matches: None
	people: None
	price: None
2019-04-02 11:51:32 DEBUG    rasa.core.agent  - deleted lock for conversation 'default' (unused)
2019-04-02 11:51:32 WARNING  asyncio  - Executing <Task finished coro=<RestInput.on_message_wrapper() done, defined at /Users/oakela/Documents/RASA/rasa_nlu/rasa/core/channels/channel.py:351> result=None created at /Users/oakela/Documents/RASA/rasa_nlu/rasa/core/channels/channel.py:372> took 0.020 seconds
[2019-04-02 11:51:32 +0200] - (sanic.access)[INFO][127.0.0.1:58466]: POST http://localhost:5005/webhooks/rest/webhook?stream=true&token=  200 -1
2019-04-02 11:51:32 INFO     sanic.access  - 
```
@Ghostvv what are your thoughts, could this be done better?

**Comment by paulaWesselmann** [comment]
It's just one slot print more than before, since now there is one for every action. This is nice to see for example when you do /restart.

**Comment by Ghostvv** [comment]
I'd say, can we print them only if previous action changed them? There is no point to print them every time after the action_listen or an utterance

**Comment by akelad** [comment]
Yeah I think I agree with that, otherwise it's too much log spamming :P

**Comment by paulaWesselmann** [comment]
I'll make another commit for this when done with my other tasks.

**Comment by wochinge** [comment]
> I'd say, can we print them only if previous action changed them? There is no point to print them every time after the action_listen or an utterance

Can we then at least print sth like "Slots didn't change" or so?

**Comment by akelad** [comment]
^ sure, but i would say it makes no sense to print that after an `action_listen`

**Comment by paulaWesselmann** [comment]
I changed it now, so that the slots will be printed after any action other than `action_listen` in debug mode. So that you can see if your slots were changed, after an action that could change them.

**Comment by paulaWesselmann** [comment]
@akelad ready for review

**Comment by akelad** [comment]
ahh i just thought of another edge case, what if the user says: "I want greek food" and that directly sets the slot? we won't see the slot change then.
I really don't know where the best place to print this stuff is :D

**Comment by paulaWesselmann** [comment]
@akelad that should be fine I think, since the user will see which entities are detected in the user message and which slots are filled. The issue was just for printing them with actions. The slots are always printed with the conversation history.

**Comment by akelad** [comment]
but you don't though, look at this interaction:
```
what kind of cuisine would you like?
Your input ->  greek
2019-04-10 14:49:04 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'default'
2019-04-10 14:49:04 DEBUG    rasa.core.processor  - Received user message 'greek' with intent '{'name': 'inform', 'confidence': 0.9999709296218549}' and entities '[{'start': 0, 'end': 5, 'value': 'greek', 'entity': 'cuisine', 'confidence': 0.9739651135051228, 'extractor': 'CRFEntityExtractor'}]'
2019-04-10 14:49:04 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 13 events
2019-04-10 14:49:04 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'intent_inform': 1.0, 'prev_utter_on_it': 1.0}, {'intent_inform': 1.0, 'prev_utter_ask_cuisine': 1.0}, {'intent_inform': 1.0, 'slot_cuisine_0': 1.0, 'prev_action_listen': 1.0, 'entity_cuisine': 1.0}]
2019-04-10 14:49:04 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2019-04-10 14:49:04 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_2_RestaurantPolicy
2019-04-10 14:49:04 DEBUG    rasa.core.processor  - Predicted next action 'utter_ask_location' with prob 0.99.
2019-04-10 14:49:04 DEBUG    rasa.core.processor  - Action 'utter_ask_location' ended with events '[]'
2019-04-10 14:49:04 DEBUG    rasa.core.processor  - Bot utterance 'BotUttered(text: where?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
2019-04-10 14:49:04 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'intent_inform': 1.0, 'prev_utter_ask_cuisine': 1.0}, {'intent_inform': 1.0, 'slot_cuisine_0': 1.0, 'prev_action_listen': 1.0, 'entity_cuisine': 1.0}, {'intent_inform': 1.0, 'prev_utter_ask_location': 1.0, 'slot_cuisine_0': 1.0, 'entity_cuisine': 1.0}]
2019-04-10 14:49:04 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2019-04-10 14:49:04 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_2_RestaurantPolicy
2019-04-10 14:49:04 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with prob 0.99.
2019-04-10 14:49:04 DEBUG    rasa.core.processor  - Action 'action_listen' ended with events '[]'
```

**Comment by paulaWesselmann** [comment]
@akelad i was still thinking about interactive learning, because there you'd get the chat history printed (including slots).
I'll try to think of something better for this case.

**Comment by paulaWesselmann** [comment]
@akelad what do you think of this idea (see file changes newest commit)? Now the slots are printed every time that an entity was detected in the user message, to show the user if this entity was used to fill a slot or not. And it's printed after actions that could fill slots.

**Comment by akelad** [comment]
yes i like that! @Ghostvv what do you think of this way?

**Comment by Ghostvv** [comment]
sounds good to me

**Pull request merged**
