### PR TITLE
Uses Spacy 2 syntax to disable dependency parser

### LINKED ISSUE #1649: SpacyNLP component: migrate to Spacy 2 way to disable the dependency parser
Spacy 2 introduced a new way to disable the dependency parser.

Instead of:
```
nlp = spacy.load(spacy_model_name, parser=False)
```

the following syntax should be used:
```
nlp = spacy.load(spacy_model_name, disable=['parser'])
```

Reference: The section "Important note: disabling pipeline components" of https://spacy.io/usage/processing-pipelines#disabling

### PR DESCRIPTION
**Pull request by Tpt**
Closes #1649

Use Spacy 2 syntax to disable dependency parser

See the note "Uses Spacy 2 syntax to disable dependency parser" in https://spacy.io/usage/processing-pipelines#disabling

### CODE REVIEW

**Comment by Tpt** [comment]
It seems to me that the Travis build failed about something not related to this pull request.

The [1406.3 Check Dependency Licenses](https://travis-ci.com/RasaHQ/rasa_nlu/jobs/173298840) job failed with:

```
2.47s$ fossa analyze
FATAL Error during upload: you do not have permission to upload builds for this project
The command "fossa analyze" exited with 1.
```

**Comment by akelad** [comment]
Thanks for submitting this PR, we'll give it a review as soon as possible! 
@tmbo can you look into why the fossa thing has failed?
@wochinge this is def a necessary contribution -- we may need to make a minor release as well. Can you check whether the old way is deprecated and also whether changes are needed anywhere else?

**Comment by tmbo** [comment]
I tried to fix this on master just now (disabling the build stages for contributor PRs as these builds aren't able to access the Fossa secrets necessary for the dependency check) - this won't fix the build here though, I will merge this once approved (don't **worry about the failing travis**)

**Comment by akelad** [comment]
i just hit update branch -- that should fix the build right?

**Comment by tmbo** [comment]
Yes :+1:

**Comment by Tpt** [comment]
@wochinge thank you! I have updated the changelog

**Comment by wochinge** [comment]
@Tpt Merged your pull request. Thanks for the contribution!

**Pull request merged**
