### PR TITLE
added spacy macther to load entitied based on lookup tables

### PR DESCRIPTION
**Pull request by sfahad1414**
added spacy matcher to load entities based on lookup tables without providing entities mapping in common examples as ner_crf only works in the combinations of common examples.

**Proposed changes**:
- added file rasa_nlu/extractors/spacy_entity_matcher.py to be included as a component in the rasa nlu pipeline.

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
Thanks for submitting this PR, we'll give it a review as soon as possible

**Comment by MetcalfeTom** [comment]
@sfahad1414 thanks for your work.  Is the code ready for review?

Some tests and changelog updates will also be necessary before merge.

**Comment by akelad** [comment]
@sfahad1414 I already commented this on the related issue, but can I ask why exactly this is needed? We decided against merging something like this before, and merged the lookup tables instead.

**Comment by sfahad1414** [comment]
@akelad Native Lookup table works only in conjunction with the common examples containing entities mapping as we are starting from scratch we need to create lookup tables and their corresponding entities mapping examples which is a tedious task as we need to provide fair enough samples for the entities in the lookup. We tried using ner_crf in the pipeline also but the same problems of not recognizing entities without sufficient examples. So we created an Extractor which works on the concept of Pattern Matching provided by Spacy for getting all the entities recognized without providing any common examples and just providing all the entities in the native lookup table.

Next we as next step we are working on the Natural Language Generation for generating common examples based on entities and their respected mapping.

**Comment by sfahad1414** [comment]
@mjordan007 could you please share the lookup you have used for pattern matching because if you have two entries/entities for new and new york than pattern matching will match both one for 'new' and another for 'new york' if you want only one entry to come up. After pattern matching has matched all the entries/entities then we need to filter out all the entries/entities which are the part on another entries/entities having a maximum length. 
an example in your case we can filter out 'new' as it is part of 'new york'

**Comment by akelad** [comment]
@sfahad1414 sorry about taking so long to get back to you about this. Yeah I understand, but we consciously decided against merging something like this. The thing is, if you don't provide some common examples, your intents won't get recognised correctly which means your model breaks anyways. Therefore we think it's better to have the lookup table and still provide some sentence examples

**Comment by mjordan007** [comment]
Yup exactly, got your point. And that's what happening. I was just curious to know whether do we have something that filters out subsets ? or we need to code it on our own and get that the way we want it?

**Comment by akelad** [comment]
@sfahad1414 thanks a lot for the contribution, but after discussing it with the team we've decided not to accept it. We were considering implementing something like this a while ago ourselves, but then decided against it in favour of the lookup tables. This is because implementing something like spacy matcher would mean that people might stop adding enough training data for intents to be recognised. The lookup tables work as intended when you add a bit of training data for those entities

**Pull request closed without merging**
