### PR TITLE
MongoDB persistence

### PR DESCRIPTION
**Pull request by dinal24**
**Proposed changes**: (Related #35)
- Reads the file system just as other persisters and uploads files to a MongoDB collection by creating a new document with binary files and JSON files (does not directly store a zip as other persisters to preserve readability of other metadata files).

**Status**:
- [x] ready for code review
- [ ] there are tests for the functionality
- [x] documentation updated
- [ ] changelog updated

### CODE REVIEW

**Comment by tmbo** [comment]
@dinal24 sorry for the delay - there is just so much going on and I have forgotten to check if Thomas reviewed this PR. 

I really like the idea of adding mongo as a persistor, so if you are still willing to merge this, let me know. So we can move this forward and get it merged as soon as possible.

**Comment by dinal24** [comment]
@tmbo Could you please give me sometime, I'll recheck if any updates are needed for accurate functionality with recent changes!

**Comment by tmbo** [comment]
That sounds great - there are a couple of merge conflicts that need to be resolved. Let me know if there is anything I can help you with.

**Comment by tmbo** [comment]
I will close this for now. Let me know if you want to pick it up again.

**Pull request closed without merging**
