### PR TITLE
Update dialogflow.com (api.ai) response emulation to new format

### PR DESCRIPTION
**Pull request by irfan-zoefit**
**Proposed changes**:
- `api.ai` now `dialogflow.com`. Change old format to new format
- related issue #509
**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by irfan-zoefit** [comment]
It seems the data object in https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/emulators/dialogflow.py does not have necessary data for the format. Also, number of parameters for contexts and keys are not designed in the way to support `dialogflow.com`

**Comment by tmbo** [comment]
What is the idea behind this PR?

**Comment by irfan-zoefit** [comment]
To support dialogflow format, but format dependent on data, the data object is not sufficient for the response.

**Comment by wrathagom** [comment]
Did you by any chance forget to commit some files? The commits so far just fix some typos and rev the version, but they don't do anything to impact the Dialogflow emulation.

Also, is there a particular reason you can't just move up to the 0.10.x latest release? it has a lot of Dialogflow related improvements.

**Pull request closed without merging**
