### PR TITLE
Enable logging requests to MongoDB

### PR DESCRIPTION
**Pull request by znat**
**Proposed changes**:
- Logging requests/responses to MongoDB

**Status**:
- [x] ready for code review
- [ ] there are tests for the functionality
- [x] documentation updated
- [x] changelog updated

I'm not sure where to add tests: DataRouter is not tested and DB ops are hard to test without mocking. Open to suggestions but can't spend hours on this :)

### CODE REVIEW

**Comment by znat** [comment]
The build fails because one requirement is missing (`txmongo`), but this requirement is only in `requirement_full`. What is the right way to fix that?

**Comment by tmbo** [comment]
@znat I am super sorry that I didn't respond yet, just wanted to assure you that this is still on the radar - will get back to this as soon as I can with the idea I described you.

**Comment by znat** [comment]
Hi @tmbo, no worries, can you remind me the idea you're looking for? Just in case I have a spark

**Comment by tmbo** [comment]
I'll close this as I don't think this is generic enough to be added to the framework. 

If there is a need for a more generic solution of this, it would probably make sense to add something similar as we added it to core recently, an event stream output (e.g. kafka or rabbitmq). You could still connect a consumer that stores the event in mongo but the benefit is that it isn't as closely bound to a db.

**Pull request closed without merging**
