### PR TITLE
wont work without food

### PR DESCRIPTION
**Pull request by phoet**
just working through the tutorial i noticed that with the given query, no entities are found. since "italian food" is used in the tests, i figured that it will do the trick.

### CODE REVIEW

**Comment by tmbo** [comment]
@phoet that is a good idea! Mind merging in the current master into your branch? (travis currently fails on PRs from forks due to the travis secret system - I fixed thaton master)

**Comment by phoet** [comment]
where is the "rebase" button in case you need one!

**Comment by tmbo** [comment]
Thanks, let's if that works (travis stages are still beta so is the documentation on them :D)

**Comment by tmbo** [comment]
Looking good :+1: thanks for the fix

**Pull request merged**
