### PR TITLE
enabled + fixed eval testing

### PR DESCRIPTION
**Pull request by twerkmeister**
**Proposed changes**:
- enabled evaluation test suite
- refactored cross validation methods

supersedes PR #817 
**Status (please check what you already did)**:
- [x] made PR ready for code review

### CODE REVIEW

**Comment by twerkmeister** [comment]
Getting different results on my machine than on travis for a test... Another one of these tests were you are lost as a dev 🤔

```
____________________________ test_run_cv_evaluation ____________________________
    def test_run_cv_evaluation():
        import numpy as np
        td = training_data.load_data('data/examples/rasa/demo-rasa.json')
        n_folds = 3
        nlu_config = RasaNLUConfig("sample_configs/config_spacy.json")
    
        np.random.seed(2018)
        results = run_cv_evaluation(td, n_folds, nlu_config)
    
        acc = np.mean(results["Accuracy"])
        exp_acc = 0.677777  # expected result
>       np.testing.assert_approx_equal(acc, exp_acc, significant=5)
E       AssertionError: 
E       Items are not equal to 5 significant digits:
E        ACTUAL: 0.8833333333333333
E        DESIRED: 0.677777
tests/base/test_evaluation.py:234: AssertionError
```

**Comment by amn41** [comment]
a random seed of `666` should resolve this in my experience

**Comment by twerkmeister** [comment]
Coverage `+4.6%` woop woop

**Comment by tmbo** [comment]
Nice :rocket: - can you please merge in master to resolve the conflicts?

**Comment by tmbo** [comment]
merged :tada: 🚀

**Pull request merged**
